query adConnectorList($userPoolId: String!, $providerType: providerType){
    adConnectorList(userPoolId: $userPoolId, providerType: $providerType){
        _id
        name
        secret
        salt
        logo
        enabled
        userPoolId
        status
        createdAt
    }
}