query clientRoles($client: String!, $page: Int, $count: Int){
    clientRoles(client: $client, page: $page, count: $count){
        list{
            _id
            name
            descriptions
            client
            permissions
            createdAt
        }
        totalCount
    }
}