query findClientsByIdArray($clientsId: [String]){
    findClientsByIdArray(clientsId: $clientsId){
        list{
            _id
            name
            createdAt
            usersCount
        }
        totalCount
    }
}