query getAllWebhooks($client: String!){
    getAllWebhooks(client: $client){
        _id
        client
        events{
            name
            label
            description
        }
        url
        isLastTimeSuccess
        contentType
        secret
        enable
    }
}