query getClientWhenSdkInit($secret: String, $clientId: String, $retUserId: Boolean, $timestamp: String, $signature: String, $nonce: Int){
    getClientWhenSdkInit(secret: $secret, clientId: $clientId, retUserId: $retUserId, timestamp: $timestamp, signature: $signature, nonce: $nonce){
        clientInfo{
            _id
            usersCount
            logo
            emailVerifiedDefault
            sendWelcomeEmail
            registerDisabled
            showWXMPQRCode
            useMiniLogin
            useSelfWxapp
            allowedOrigins
            name
            secret
            token
            descriptions
            jwtExpired
            createdAt
            isDeleted
            enableEmail
        }
        accessToken
    }
}