query getOAuthedAppList($clientId: String, $page: Int, $count: Int){
    getOAuthedAppList(clientId: $clientId, page: $page, count: $count){
        totalCount
        list{
            _id
            name
            domain
            image
            redirectUris
            appSecret
            client_id
            clientId
            grants
            description
            homepageURL
            isDeleted
            when
            css
            loginUrl
            casExpire
        }
    }
}