query GetUserAuthorizedApps($clientId: String, $userId: String, $page: Int, $count: Int){
    GetUserAuthorizedApps(clientId: $clientId, userId: $userId, page: $page, count: $count){
        totalCount
        OAuthApps{
            _id
            name
            domain
            image
            redirectUris
            appSecret
            client_id
            clientId
            grants
            description
            homepageURL
            isDeleted
            when
            css
            loginUrl
            casExpire
        }
        OIDCApps{
            _id
            name
            domain
            image
            redirect_uris
            client_id
            client_secret
            token_endpoint_auth_method
            id_token_signed_response_alg
            id_token_encrypted_response_alg
            id_token_encrypted_response_enc
            userinfo_signed_response_alg
            userinfo_encrypted_response_alg
            userinfo_encrypted_response_enc
            request_object_signing_alg
            request_object_encryption_alg
            request_object_encryption_enc
            jwks_uri
            _jwks_uri
            custom_jwks
            jwks
            _jwks
            clientId
            grant_types
            response_types
            description
            homepageURL
            isDeleted
            isDefault
            when
            css
            authorization_code_expire
            id_token_expire
            access_token_expire
            cas_expire
            loginUrl
        }
    }
}