query getWebhookLogs($webhook: String!){
    getWebhookLogs(webhook: $webhook){
        _id
        webhook
        client
        event
        request{
            headers
            payload
        }
        response{
            headers
            body
            statusCode
        }
        errorMessage
        when
    }
}