query getWebhookSettingOptions{
    getWebhookSettingOptions{
        webhookEvents{
            name
            label
            description
        }
        contentTypes{
            name
            label
        }
    }
}