query orgChildrenNodes($input: OrgChildrenNodesInput!){
    orgChildrenNodes(input: $input){
        group{
            _id
            userPoolId
            name
            description
            createdAt
            updatedAt
        }
        depth
    }
}