query QuerySAMLServiceProviderInfoByAppID($appId: String!){
    QuerySAMLServiceProviderInfoByAppID(appId: $appId){
        _id
        name
        domain
        image
        appSecret
        defaultIdPMap{
            _id
            name
            image
            description
            isDeleted
        }
        defaultIdPMapId
        appId
        clientId
        description
        isDeleted
        enabled
        when
        SPMetadata
        IdPMetadata
        IdPEntityID
        assertionConsumeService{
            binding
            url
            isDefault
        }
        mappings{
            username
            nickname
            photo
            company
            providerName
            email
        }
        redirectUrl
        loginUrl
        logoutUrl
        nameId
        enableSignRes
        resSignPublicKey
        hasResEncrypted
        resEncryptAlgorithm
        resAbstractAlgorithm
        resDecryptPrivateKey
        resDecryptPrivateKeyPass
        resEncryptPublicKey
        enableSignReq
        reqSignAlgorithm
        reqAbstractAlgorithm
        reqSignPrivateKey
        reqSignPrivateKeyPass
        reqSignPublicKey
        SPUrl
    }
}