query queryUserPoolCommonInfo($userPoolId: String!){
    queryUserPoolCommonInfo(userPoolId: $userPoolId){
        _id
        changePhoneStrategy{
            verifyOldPhone
        }
        changeEmailStrategy{
            verifyOldEmail
        }
    }
}