query queryProviderInfoByAppId($appId: String){
    queryProviderInfoByAppId(appId: $appId){
        _id
        type
        name
        image
        domain
        clientId
        client_id
        css
        redirect_uris
    }
}