query queryMFA($_id: String, $userId: String, $userPoolId: String){
    queryMFA(_id: $_id, userId: $userId, userPoolId: $userPoolId){
        _id
        userId
        userPoolId
        enable
        shareKey
    }
}