query ReadEmailProvider($clientId: String){
    ReadEmailProvider(clientId: $clientId){
        _id
        name
        image
        description
        fields{
            label
            type
            placeholder
            help
            value
            options
        }
        client
        user
        status
        provider{
            _id
            name
            image
            description
            client
            user
            status
        }
    }
}