query ReadEmailSentList($page: Int, $count: Int, $sortBy: String){
    ReadEmailSentList(page: $page, count: $count, sortBy: $sortBy){
        list{
            _id
            subject
            content
            sender
            receivers
            createdAt
        }
        totalCount
    }
}