query ReadEmailProviderByClientAndName($clientId: String){
    ReadEmailProviderByClientAndName(clientId: $clientId){
        _id
        user
        client
        status
        fields{
            label
            type
            placeholder
            help
            value
            options
        }
        provider{
            _id
            name
            image
            description
        }
    }
}