query ReadOrders($user: String, $page: Int, $count: Int){
    ReadOrders(user: $user, page: $page, count: $count){
        list{
            _id
            client
            user
            timeOfPurchase
            flowNumber
            price
            createdAt
            completed
            payMethod
            endAt
        }
        totalCount
    }
}