query ruleById($_id: String!){
    ruleById(_id: $_id){
        _id
        userPoolId
        name
        description
        type
        enabled
        faasUrl
        code
        order
        async
        createdAt
        updatedAt
    }
}