query statistic($sortBy: String, $page: Int, $count: Int){
    statistic(sortBy: $sortBy, page: $page, count: $count){
        list{
            _id
            username
            email
            loginsCount
            appsCount
            OAuthCount
        }
        totalCount
    }
}