query usersInGroup($group: String, $page: Int, $count: Int){
    usersInGroup(group: $group, page: $page, count: $count){
        list{
            email
            username
            _id
            upgrade
        }
        totalCount
    }
}