query userPermissionList($_id: String!){
    userPermissionList(_id: $_id){
        totalCount
        list{
            _id
            name
            userPoolId
            createdAt
            updatedAt
            description
        }
        rawList
    }
}