query wxQRCodeLog($page: Int, $count: Int, $clientId: String, $sortBy: String){
    wxQRCodeLog(page: $page, count: $count, clientId: $clientId, sortBy: $sortBy){
        list{
            random
            expiredAt
            createdAt
            success
            qrcode
            used
            accessToken
            openid
            userInfo
            redirect
        }
        totalCount
    }
}