query loginCount($userId: String, $clientId: String, $month: String){
    loginCount(userId: $userId, clientId: $clientId, month: $month){
        _id
        client
        count
        month
        isError
        totalNumber
    }
}