query queryClient($id: String!){
    queryClient(id: $id){
        _id
        usersCount
        logo
        emailVerifiedDefault
        registerDisabled
        showWXMPQRCode
        useMiniLogin
        useSelfWxapp
        allowedOrigins
        name
        secret
        token
        descriptions
        jwtExpired
        createdAt
        isDeleted
        enableEmail
    }
}