query QueryAppInfoByAppID($appId: String, $responseType: String, $redirectUrl: String){
    QueryAppInfoByAppID(appId: $appId, responseType: $responseType, redirectUrl: $redirectUrl){
        _id
        name
        domain
        image
        redirectUris
        appSecret
        client_id
        clientId
        grants
        description
        homepageURL
        isDeleted
        when
        css
        loginUrl
        casExpire
    }
}