query queryCollaborationByUserPoolIdAndUserId($userId: String!, $userPoolId: String!){
    queryCollaborationByUserPoolIdAndUserId(userId: $userId, userPoolId: $userPoolId){
        _id
        createdAt
    }
}