query queryPasswordFaasEnabled($client: String!){
    queryPasswordFaasEnabled(client: $client){
        encryptUrl
        decryptUrl
        user
        client
        logs
        enable
        createdAt
        updatedAt
    }
}