query queryAuthAuditRecords($userPoolId: String!, $sortBy: String, $page: Int, $count: Int){
    queryAuthAuditRecords(userPoolId: $userPoolId, sortBy: $sortBy, page: $page, count: $count){
        totalCount
    }
}