query ReadEmailTemplateByClientAndType($type: String!, $client: String!){
    ReadEmailTemplateByClientAndType(type: $type, client: $client){
        _id
        type
        sender
        object
        hasURL
        URLExpireTime
        status
        redirectTo
        content
    }
}