query users($registerInClient: String, $page: Int, $count: Int, $populate: Boolean){
    users(registerInClient: $registerInClient, page: $page, count: $count, populate: $populate){
        totalCount
    }
}