query validatePassword($userPool: String!, $password: String!, $encryptedPassword: String!){
    validatePassword(userPool: $userPool, password: $password, encryptedPassword: $encryptedPassword){
        isValid
    }
}